apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      # Azure AD tenant ID
      tenantId: "REPLACE_WITH_TENANT_ID"
      # Azure Key Vault URL (not a secret)
      vaultUrl: "https://REPLACE_WITH_KEYVAULT_NAME.vault.azure.net"
      # Recommended auth for AKS: Azure Workload Identity
      authType: WorkloadIdentity
      serviceAccountRef:
        # ServiceAccount created by the ESO helm chart (see aks-rocketchat-external-secrets ArgoCD app)
        name: external-secrets
        namespace: external-secrets

