# External Secrets Operator: ClusterSecretStore for Azure Key Vault
# This ClusterSecretStore configures ESO to authenticate to Azure Key Vault using Azure Workload Identity.
# It's used by ExternalSecrets in ops/secrets/*.yaml to sync secrets from Key Vault to Kubernetes.
# See VERSIONS.md for External Secrets Operator version tracking (managed by Helm chart via ArgoCD).
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault  # ClusterSecretStore name (referenced by ExternalSecrets via spec.secretStoreRef)
spec:
  provider:
    azurekv:
      # Azure Key Vault provider configuration
      # Azure AD tenant ID (from Terraform outputs or Azure CLI: az account show --query tenantId)
      tenantId: "c3d431f1-3e02-4c62-a825-79cd8f9e2053"
      # Azure Key Vault URL (not a secret - can be found in Azure Portal or Terraform outputs)
      # Format: https://<vault-name>.vault.azure.net
      vaultUrl: "https://aks-canepro-kv-e8d280.vault.azure.net"
      # Recommended auth for AKS: Azure Workload Identity (uses ServiceAccount tokens)
      # Workload Identity is more secure than service principal keys (no secrets in cluster)
      authType: WorkloadIdentity
      serviceAccountRef:
        # ServiceAccount created by the ESO helm chart (see aks-rocketchat-external-secrets ArgoCD app)
        # This ServiceAccount has Azure Workload Identity annotations and is used to authenticate to Key Vault
        name: external-secrets  # ServiceAccount name (must match ESO Helm chart serviceAccount.name)
        namespace: external-secrets  # ServiceAccount namespace (must match ESO Helm chart namespace)

