# External Secrets Operator: Jenkins Credentials
# This ExternalSecret syncs Jenkins credentials from Azure Key Vault to Kubernetes Secret.
# Secrets include: admin username/password, GitHub token for PR validation.
# Created by: ESO controller watching this resource.
# Used by: Jenkins controller pod (credentials for admin login + GitHub integration).
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-admin  # ExternalSecret name (creates Secret with same name)
  namespace: jenkins  # Target namespace (must match Jenkins deployment namespace)
spec:
  # Refresh interval: How often to sync secrets from Key Vault
  refreshInterval: 1h  # Sync every 1 hour (adjust as needed)
  
  # Secret store reference: ClusterSecretStore to use for authentication
  secretStoreRef:
    name: azure-keyvault  # ClusterSecretStore name (from ops/secrets/clustersecretstore-azure-keyvault.yaml)
    kind: ClusterSecretStore  # Resource kind
  
  # Target secret: Kubernetes Secret to create/update
  target:
    name: jenkins-admin  # Secret name (referenced by jenkins-values.yaml controller.admin.existingSecret)
    creationPolicy: Owner  # ESO owns the secret (will delete if ExternalSecret is deleted)
  
  # Data mapping: Map Key Vault secrets to Kubernetes Secret keys
  data:
    # Admin username: Jenkins admin username
    - secretKey: username  # Kubernetes Secret key (referenced by jenkins-values.yaml controller.admin.userKey)
      remoteRef:
        key: jenkins-admin-username  # Key Vault secret name (from terraform/keyvault.tf)
    
    # Admin password: Jenkins admin password
    - secretKey: password  # Kubernetes Secret key (referenced by jenkins-values.yaml controller.admin.passwordKey)
      remoteRef:
        key: jenkins-admin-password  # Key Vault secret name (from terraform/keyvault.tf)

---
# External Secrets Operator: Jenkins GitHub Token
# This ExternalSecret syncs Jenkins GitHub token from Azure Key Vault to Kubernetes Secret.
# Used by: Jenkins GitHub plugin for PR validation and webhook management.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-github  # ExternalSecret name (creates Secret with same name)
  namespace: jenkins  # Target namespace (must match Jenkins deployment namespace)
spec:
  # Refresh interval: How often to sync secrets from Key Vault
  refreshInterval: 1h  # Sync every 1 hour (adjust as needed)
  
  # Secret store reference: ClusterSecretStore to use for authentication
  secretStoreRef:
    name: azure-keyvault  # ClusterSecretStore name (from ops/secrets/clustersecretstore-azure-keyvault.yaml)
    kind: ClusterSecretStore  # Resource kind
  
  # Target secret: Kubernetes Secret to create/update
  target:
    name: jenkins-github  # Secret name (referenced by Jenkins credentials)
    creationPolicy: Owner  # ESO owns the secret (will delete if ExternalSecret is deleted)
  
  # Data mapping: Map Key Vault secrets to Kubernetes Secret keys
  data:
    # GitHub token: Personal access token for GitHub API access
    - secretKey: token  # Kubernetes Secret key (referenced by Jenkins GitHub plugin)
      remoteRef:
        key: jenkins-github-token  # Key Vault secret name (from terraform/keyvault.tf)
