apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rocketchat-mongodb-external
  namespace: rocketchat
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: rocketchat-mongodb-external
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: mongo-uri
      remoteRef:
        # AKV secret name
        key: rocketchat-mongo-uri
    - secretKey: mongo-oplog-uri
      remoteRef:
        # AKV secret name
        key: rocketchat-mongo-oplog-uri

