# ExternalSecret: MongoDB Metrics Endpoint Password (Monitoring Namespace)
# This mirrors the MongoDB metrics endpoint password into the `monitoring` namespace
# so Prometheus Agent can scrape the MongoDB metrics endpoint (basic auth protected)
# without committing credentials to git.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-metrics-endpoint-password
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: mongodb-metrics-endpoint-password
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: password
      remoteRef:
        key: rocketchat-mongodb-metrics-endpoint-password

