# ExternalSecret: Observability Credentials
# This ExternalSecret syncs observability credentials (Grafana username/password) from Azure Key Vault to a Kubernetes Secret.
# Used by Prometheus Agent, OTel Collector, and Promtail for authenticating to the central observability hub.
# See VERSIONS.md for External Secrets Operator version tracking (managed by Helm chart via ArgoCD).
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: observability-credentials  # ExternalSecret name (also used as target Secret name)
  namespace: monitoring  # Namespace for observability components (Prometheus Agent, OTel Collector, Promtail)
spec:
  refreshInterval: 1h  # How often to sync from Key Vault (1 hour)
  secretStoreRef:
    # Reference to ClusterSecretStore (see clustersecretstore-azure-keyvault.yaml)
    name: azure-keyvault  # ClusterSecretStore name (from ops/secrets/clustersecretstore-azure-keyvault.yaml)
    kind: ClusterSecretStore  # ClusterSecretStore kind (cluster-scoped secret store)
  target:
    name: observability-credentials  # Kubernetes Secret name (created by ESO, used by Prometheus Agent, OTel Collector, Promtail)
    creationPolicy: Owner  # ESO owns the Secret (can delete/modify it)
    template:
      type: Opaque  # Secret type (allows arbitrary key-value pairs)
  data:
    # Secret keys to sync from Key Vault
    # Username: Grafana username or instance ID for basic auth
    - secretKey: username  # Kubernetes Secret key name (referenced as ${GRAFANA_USERNAME} in ConfigMaps)
      remoteRef:
        # Azure Key Vault secret name (from terraform/keyvault.tf)
        key: rocketchat-observability-username  # Key Vault secret name (created by Terraform)
    # Password: Grafana API key or password for basic auth
    - secretKey: password  # Kubernetes Secret key name (referenced as ${GRAFANA_PASSWORD} in ConfigMaps)
      remoteRef:
        # Azure Key Vault secret name (from terraform/keyvault.tf)
        key: rocketchat-observability-password  # Key Vault secret name (created by Terraform)
