apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: production-cert-issuer
spec:
  acme:
    # The ACME server URL for Let's Encrypt production
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mogah.vincent@hotmail.com
    privateKeySecretRef:
      name: production-cert-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: traefik

