# ArgoCD Application: Rocket.Chat Operations Infrastructure
# This ArgoCD Application deploys operational infrastructure for the AKS Rocket.Chat deployment.
# It includes: NATS, Prometheus Agent, OTel Collector, Promtail, PVCs, cert-manager ClusterIssuer, and maintenance jobs.
# See VERSIONS.md for version tracking of all components managed by this application.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks-rocketchat-ops
  namespace: argocd
  labels:
    app: rocketchat-ops  # Application identifier in ArgoCD
    cluster: aks-canepro  # Cluster identifier for filtering in ArgoCD
spec:
  project: default  # ArgoCD project (controls permissions and allowed resources)
  source:
    repoURL: https://github.com/Canepro/rocketchat-k8s.git  # Git repository URL
    targetRevision: master  # Branch/tag to deploy
    path: ops  # Path to kustomization.yaml (this directory contains all ops manifests)
    kustomize:
      # Kustomize will handle resources in multiple namespaces automatically
      # Resources in ops/manifests/ and ops/secrets/ include namespace declarations
      # Namespaces: rocketchat (NATS, PVCs) and monitoring (observability stack)
  destination:
    server: https://aks-canepro-wfcra91z.hcp.uksouth.azmk8s.io:443  # AKS cluster API server
    # Kustomize manages multiple namespaces, but ArgoCD requires a default namespace
    # The actual namespaces are defined in the manifest files (metadata.namespace)
    namespace: rocketchat  # Default namespace (for ArgoCD, not all resources)
  syncPolicy:
    # Automated sync: Automatically sync when Git changes are detected
    automated:
      prune: true  # Automatically delete resources removed from Git
      selfHeal: true  # Automatically fix drift (revert manual changes to match Git)
    syncOptions:
      - CreateNamespace=true  # Automatically create namespaces if they don't exist
      - PrunePropagationPolicy=foreground  # Wait for dependent resources to be deleted first
      - PruneLast=true  # Delete resources last (after creating new ones)
    retry:
      # Retry configuration: Retry failed syncs with exponential backoff
      limit: 5  # Maximum number of retry attempts
      backoff:
        duration: 5s  # Initial retry delay
        factor: 2  # Exponential backoff multiplier
        maxDuration: 3m  # Maximum retry delay
