apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks-rocketchat-helm
  namespace: argocd
  labels:
    app: rocketchat
    cluster: aks-canepro
spec:
  project: default
  sources:
    # Helm chart from Rocket.Chat Helm repository
    - repoURL: https://rocketchat.github.io/helm-charts
      chart: rocketchat
      targetRevision: 6.28.0
      helm:
        releaseName: rocketchat
    # Values from Git repository
    - ref: values
      repoURL: https://github.com/Canepro/rocketchat-k8s.git
      targetRevision: aks-migration
      helm:
        valueFiles:
          - values.yaml
  destination:
    server: https://aks-canepro-wfcra91z.hcp.uksouth.azmk8s.io:443
    namespace: rocketchat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
