apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks-rocketchat-secrets
  namespace: argocd
  labels:
    app: rocketchat-secrets
    cluster: aks-canepro
spec:
  project: default
  source:
    repoURL: https://github.com/Canepro/rocketchat-k8s.git
    targetRevision: aks-migration
    path: ops/secrets
  destination:
    server: https://aks-canepro-wfcra91z.hcp.uksouth.azmk8s.io:443
    namespace: rocketchat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

