# ArgoCD Application: Rocket.Chat Secrets (GitOps)
# This ArgoCD Application deploys GitOps secrets management resources.
# It includes: ClusterSecretStore (Azure Key Vault auth) and ExternalSecrets (secret sync definitions).
# Secret values are stored in Azure Key Vault (not in Git) and synced to Kubernetes Secrets by ESO.
# See VERSIONS.md for version tracking of ESO components.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks-rocketchat-secrets
  namespace: argocd
  labels:
    app: rocketchat-secrets  # Application identifier in ArgoCD
    cluster: aks-canepro  # Cluster identifier for filtering in ArgoCD
spec:
  project: default  # ArgoCD project (controls permissions and allowed resources)
  source:
    repoURL: https://github.com/Canepro/rocketchat-k8s.git  # Git repository URL
    targetRevision: master  # Branch/tag to deploy
    path: ops/secrets  # Path to kustomization.yaml (contains ClusterSecretStore and ExternalSecrets)
  destination:
    server: https://aks-canepro-wfcra91z.hcp.uksouth.azmk8s.io:443  # AKS cluster API server
    namespace: rocketchat  # Target namespace (most ExternalSecrets target this namespace)
  syncPolicy:
    # Automated sync: Automatically sync when Git changes are detected
    automated:
      prune: true  # Automatically delete resources removed from Git
      selfHeal: true  # Automatically fix drift (revert manual changes to match Git)
    syncOptions:
      - CreateNamespace=true  # Automatically create namespace if it doesn't exist
      - PrunePropagationPolicy=foreground  # Wait for dependent resources to be deleted first
      - PruneLast=true  # Delete resources last (after creating new ones)
    retry:
      # Retry configuration: Retry failed syncs with exponential backoff
      limit: 5  # Maximum number of retry attempts
      backoff:
        duration: 5s  # Initial retry delay
        factor: 2  # Exponential backoff multiplier
        maxDuration: 3m  # Maximum retry delay

