apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks-rocketchat-external-secrets
  namespace: argocd
  labels:
    app: external-secrets
    cluster: aks-canepro
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    # Pin this to a tested chart version for your environment.
    # (Update after verifying against the upstream chart repo index.)
    targetRevision: 0.10.5
    helm:
      releaseName: external-secrets
      values: |
        installCRDs: true
        serviceAccount:
          create: true
          name: external-secrets
          annotations:
            # Azure Workload Identity client id (UAMI clientId)
            azure.workload.identity/client-id: "fe3d3d95-fb61-4a42-8d82-ec0852486531"
        podLabels:
          # Required for Azure Workload Identity token injection
          azure.workload.identity/use: "true"
  destination:
    server: https://aks-canepro-wfcra91z.hcp.uksouth.azmk8s.io:443
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

