#!/bin/bash
# Helper script to create security remediation PRs or issues based on scan results
# This can be called from Jenkins pipelines or run manually

set -euo pipefail

# Configuration
GITHUB_REPO="${GITHUB_REPO:-Canepro/rocketchat-k8s}"
GITHUB_TOKEN="${GITHUB_TOKEN:-}"
RISK_REPORT="${RISK_REPORT:-risk-assessment.json}"

# Get GitHub token from Jenkins credentials or environment
if [ -z "${GITHUB_TOKEN}" ]; then
  # Try to get from Jenkins credentials (if running in Jenkins)
  if [ -n "${GITHUB_TOKEN_CREDENTIALS:-}" ]; then
    # In Jenkins, credentials are injected via withCredentials
    GITHUB_TOKEN="${GITHUB_TOKEN}"
  else
    echo "❌ GITHUB_TOKEN not set. Please provide GitHub token:"
    read -rs GITHUB_TOKEN
    echo ""
  fi
fi

if [ ! -f "${RISK_REPORT}" ]; then
  echo "❌ Risk assessment report not found: ${RISK_REPORT}"
  exit 1
fi

# Read risk assessment
CRITICAL=$(jq -r '.critical' "${RISK_REPORT}")
HIGH=$(jq -r '.high' "${RISK_REPORT}")
MEDIUM=$(jq -r '.medium' "${RISK_REPORT}")
LOW=$(jq -r '.low' "${RISK_REPORT}")
RISK_LEVEL=$(jq -r '.risk_level' "${RISK_REPORT}")
ACTION_REQUIRED=$(jq -r '.action_required' "${RISK_REPORT}")

echo "Risk Assessment:"
echo "  Critical: ${CRITICAL}"
echo "  High: ${HIGH}"
echo "  Medium: ${MEDIUM}"
echo "  Low: ${LOW}"
echo "  Risk Level: ${RISK_LEVEL}"
echo "  Action Required: ${ACTION_REQUIRED}"

if [ "${ACTION_REQUIRED}" != "true" ]; then
  echo "✅ No action required. Risk level is acceptable."
  exit 0
fi

# Determine action based on risk level
if [ "${RISK_LEVEL}" = "CRITICAL" ] || [ "${CRITICAL}" -ge 10 ]; then
  echo "🚨 Creating GitHub issue for CRITICAL findings..."
  
  ISSUE_BODY=$(cat <<EOF
{
  "title": "🚨 Security: Critical vulnerabilities detected",
  "body": "## Security Scan Results\\n\\n**Risk Level:** CRITICAL\\n\\n**Findings:**\\n- Critical: ${CRITICAL}\\n- High: ${HIGH}\\n- Medium: ${MEDIUM}\\n- Low: ${LOW}\\n\\n## Action Required\\n\\nPlease review the security scan results and address critical vulnerabilities immediately.\\n\\n## Next Steps\\n\\n1. Review all critical findings in Jenkins build artifacts\\n2. Create remediation PRs for each critical issue\\n3. Update security policies if needed\\n\\n---\\n*This issue was automatically created by Jenkins security validation pipeline.*",
  "labels": ["security", "critical", "automated"]
}
EOF
)
  
  curl -X POST \
    -H "Authorization: token ${GITHUB_TOKEN}" \
    -H "Accept: application/vnd.github.v3+json" \
    "https://api.github.com/repos/${GITHUB_REPO}/issues" \
    -d "${ISSUE_BODY}"
    
elif [ "${HIGH}" -ge 20 ]; then
  echo "⚠️ Creating PR for HIGH priority findings..."
  
  # Create branch
  BRANCH_NAME="security/automated-fixes-$(date +%Y%m%d-%H%M%S)"
  git config user.name "Jenkins Security Bot" || true
  git config user.email "jenkins@canepro.me" || true
  git checkout -b "${BRANCH_NAME}" || git checkout "${BRANCH_NAME}"
  
  # Create security fixes documentation
  cat > SECURITY_FIXES.md <<EOF
# Security Fixes

This PR addresses high-priority security findings from automated scans.

## Findings Summary
- Critical: ${CRITICAL}
- High: ${HIGH}
- Medium: ${MEDIUM}
- Low: ${LOW}

## Automated Fixes

This PR includes automated fixes for high-priority security issues.
Please review all changes before merging.

## Manual Review Required

Some findings may require manual review and cannot be auto-fixed.
Please check the Jenkins build logs for detailed findings.
EOF
  
  git add SECURITY_FIXES.md
  git commit -m "security: automated fixes for high-priority findings

- Addresses ${HIGH} high-priority security findings
- Generated by Jenkins security validation pipeline
- Review required before merging" || true
  
  git push origin "${BRANCH_NAME}" || true
  
  # Create PR
  PR_BODY=$(cat <<EOF
{
  "title": "🔒 Security: Automated fixes for high-priority findings",
  "head": "${BRANCH_NAME}",
  "base": "master",
  "body": "## Automated Security Fixes\\n\\nThis PR addresses **${HIGH} high-priority** security findings detected by automated scans.\\n\\n### Findings Summary\\n- Critical: ${CRITICAL}\\n- High: ${HIGH}\\n- Medium: ${MEDIUM}\\n- Low: ${LOW}\\n\\n### Changes\\n\\nThis PR includes automated fixes for high-priority security issues. Please review all changes carefully.\\n\\n### Review Checklist\\n\\n- [ ] Review all automated changes\\n- [ ] Verify fixes don't break functionality\\n- [ ] Test in staging if applicable\\n- [ ] Check for any manual fixes needed\\n\\n---\\n*This PR was automatically created by Jenkins security validation pipeline.*",
  "labels": ["security", "automated", "dependencies"]
}
EOF
)
  
  curl -X POST \
    -H "Authorization: token ${GITHUB_TOKEN}" \
    -H "Accept: application/vnd.github.v3+json" \
    "https://api.github.com/repos/${GITHUB_REPO}/pulls" \
    -d "${PR_BODY}"
    
  echo "✅ PR created: ${BRANCH_NAME}"
else
  echo "ℹ️ Risk level is ${RISK_LEVEL}. Monitoring recommended but no immediate action required."
fi
